[package]
name = "prop_house"
version = "0.1.0"
description = "Public infrastructure by Nouns DAO"

[scripts]
sierra = "cairo-compile . -r"
test = "cairo-test ."
# Add your own custom commands and run them with scarb run <command>

# Uncomment if you want to use dependencies
# Note: currently testing doesn't work with dependencies
# [dependencies]
# quaireaux = { git = "https://github.com/keep-starknet-strange/quaireaux.git" }

[[target.starknet-contract]]
